# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d93005e51bfadca6cd39f29b3782018863102a36708724a32e742a4a3356699e8afeef75a0406fa9cea986eeb914fff1a730b333f4b7775ffa0b50fb336c79f3

test:
  secret_key_base: e312906e143d755b5c1aeb71b4fce64d2244ca59ff31aeaaddff8fda0dbd1cc76cfc2f87917050ccc6df1a0213197366baa4800e7308eb85b7d19fe06d78c9d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
